import os

PATH = os.path.join("Translation", "zh-Hans", "Text",
                    "_AutoGeneratedTranslations.txt")


def load():
    with open(PATH, "r", encoding="utf-8") as fn:
        ori = fn.readlines()

    ori_dict = {}
    for i in ori:
        tmp = i.split("=")
        j, k = tmp[0], tmp[1]
        ori_dict[j] = k
    return ori_dict


def save(fin_dict):
    with open(PATH, "w", encoding="utf-8") as fn:
        for i in fin_dict:
            fn.write(i+"="+fin_dict[i])


save(load())